# Site Settings
title: Nick Hood | Blog and CV
email: nick@cullaloe.com
description: Personal blog and CV repository.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cv.cullaloe.com" # the base hostname & protocol for your site
google_analytics: "UA-29333042-2"

# User Settings
username: Nick Hood @cullaloe
user_description: Educator, physicist, technophile.
disqus_username: cullaloe

# Social Media
# Remove the item if you don't need it
github_username: cullaloe
facebook_username: cullaloe
twitter_username: cullaloe
instagram_username: cullaloe
linkedin_username: cullaloe
# medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
paginate: 12
paginate_path: "/page/:num/"
svg_color: "#ff0a16"

# Plugins
plugins:
  - jemoji
  - jekyll-paginate

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

include: ['_pages']

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
